### ISSUE TITLE
java.io.FileNotFoundException: /data0/storm-0.9.1/tmp -Dstorm.jar=exclamation_topology.jar (Is a directory)

### ISSUE THREAD

**Issue by a-whitej** [Yelp/pyleus#102]
jdk1.7.0_72
zeromq-3.2.2
storm-0.9.1
zookeeper-3.4.6

pyleus local --debug  exclamation_topology.jar  

10492 [Thread-8] ERROR backtype.storm.event - Error when processing event
java.io.FileNotFoundException: /data0/storm-0.9.1/tmp -Dstorm.jar=exclamation_topology.jar (Is a directory)
        at java.util.zip.ZipFile.open(Native Method) ~[na:1.7.0_72]
        at java.util.zip.ZipFile.<init>(ZipFile.java:215) ~[na:1.7.0_72]
        at java.util.zip.ZipFile.<init>(ZipFile.java:145) ~[na:1.7.0_72]
        at java.util.zip.ZipFile.<init>(ZipFile.java:116) ~[na:1.7.0_72]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_72]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_72]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_72]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_72]
        at clojure.lang.Reflector.invokeConstructor(Reflector.java:180) ~[clojure-1.4.0.jar:na]
        at backtype.storm.util$zip_contains_dir_QMARK_.invoke(util.clj:758) ~[storm-core-0.9.1-incubating.jar:0.9.1-incubating]
        at backtype.storm.daemon.supervisor$resources_jar$fn__6343.invoke(supervisor.clj:474) ~[na:na]
        at clojure.core$filter$fn__4106.invoke(core.clj:2480) ~[clojure-1.4.0.jar:na]
        at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[clojure-1.4.0.jar:na]
        at clojure.lang.LazySeq.seq(LazySeq.java:60) ~[clojure-1.4.0.jar:na]
        at clojure.lang.LazySeq.first(LazySeq.java:82) ~[clojure-1.4.0.jar:na]
        at clojure.lang.RT.first(RT.java:566) ~[clojure-1.4.0.jar:na]
        at clojure.core$first.invoke(core.clj:55) ~[clojure-1.4.0.jar:na]
        at backtype.storm.daemon.supervisor$resources_jar.invoke(supervisor.clj:472) ~[storm-core-0.9.1-incubating.jar:0.9.1-incubating]
        at backtype.storm.daemon.supervisor$eval6348$fn__6349.invoke(supervisor.clj:482) ~[na:na]
        at clojure.lang.MultiFn.invoke(MultiFn.java:172) ~[clojure-1.4.0.jar:na]
        at backtype.storm.daemon.supervisor$mk_synchronize_supervisor$this__6251.invoke(supervisor.clj:325) ~[na:na]
        at backtype.storm.event$event_manager$fn__2921.invoke(event.clj:39) ~[na:na]
        at clojure.lang.AFn.run(AFn.java:24) [clojure-1.4.0.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_72]
10506 [Thread-8] INFO  backtype.storm.util - Halting process: ("Error when processing an event")
pyleus local: error: [StormError] Storm command failed. Run with --verbose for more info.

**Comment by a-whitej** [comment]
$ cat /etc/pyleus.conf 
[storm]
# path to Storm executable (pyleus will automatically look in PATH)
storm_cmd_path: /data0/storm-0.9.1/bin/storm

# optional: use -n option of pyleus CLI instead
nimbus_host: 10.13.3.225

# optional: use -p option of pyleus CLI instead
nimbus_port: 6628

# java options to pass to Storm CLI
#jvm_opts: -Djava.io.tmpdir=/data0/storm-0.9.1/tmp

[build]
# PyPI server to use during the build of your topologies
pypi_index_url: http://pypi.ninjacorp.com/simple/

# always use system-site-packages for pyleus virtualenvs (default: false)
system_site_packages: true

# list of packages to always include in your topologies
#include_packages: foo bar<4.0 baz==0.1

**Comment by a-whitej** [comment]
$ll /data0/storm-0.9.1/tmp
total 0

The directory '/data0/storm-0.9.1/tmp' has been there.
