### ISSUE TITLE
_serializer.read_msg return integer instead of object

### ISSUE THREAD

**Issue by a-whitej** [Yelp/pyleus#103]
(1)env
jdk1.7.0_72
zeromq-3.2.2
storm-0.9.1
zookeeper-3.4.6

(2)cmd
pyleus local --debug exclamation_topology.jar 

(3)error msg
```
12273 [Thread-21-words] ERROR backtype.storm.util - Async loop died!
java.lang.RuntimeException: Pipe to subprocess seems to be broken! Currently read output: ��pid�i��msg�FTraceback (most recent call last):
  File "/data0/sina_cre/install/python/lib/python2.7/site-packages/pyleus/storm/component.py", line 232, in run
    self.setup_component()
  File "/data0/sina_cre/install/python/lib/python2.7/site-packages/pyleus/storm/component.py", line 192, in setup_component
    self.conf, self.context = self._init_component()
  File "/data0/sina_cre/install/python/lib/python2.7/site-packages/pyleus/storm/component.py", line 306, in _init_component
    self._create_pidfile(setup_info['pidDir'], pid)
TypeError: 'int' object has no attribute '__getitem__'
�command�error
Shell Process Exception:


        at backtype.storm.utils.ShellProcess.readString(ShellProcess.java:135) ~[storm-core-0.9.1-incubating.jar:0.9.1-incubating]
        at backtype.storm.utils.ShellProcess.readMessage(ShellProcess.java:81) ~[storm-core-0.9.1-incubating.jar:0.9.1-incubating]
        at backtype.storm.utils.ShellProcess.launch(ShellProcess.java:62) ~[storm-core-0.9.1-incubating.jar:0.9.1-incubating]
        at backtype.storm.spout.ShellSpout.open(ShellSpout.java:53) ~[storm-core-0.9.1-incubating.jar:0.9.1-incubating]
        at backtype.storm.daemon.executor$eval5100$fn__5101$fn__5116.invoke(executor.clj:519) ~[na:na]
        at backtype.storm.util$async_loop$fn__390.invoke(util.clj:431) ~[na:na]
        at clojure.lang.AFn.run(AFn.java:24) [clojure-1.4.0.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_72]
12273 [Thread-19-exclaim2] ERROR backtype.storm.util - Async loop died!
java.lang.RuntimeException: Pipe to subprocess seems to be broken! Currently read output: ��pid�c��msg�FTraceback (most recent call last):
  File "/data0/sina_cre/install/python/lib/python2.7/site-packages/pyleus/storm/component.py", line 232, in run
    self.setup_component()
  File "/data0/sina_cre/install/python/lib/python2.7/site-packages/pyleus/storm/component.py", line 192, in setup_component
    self.conf, self.context = self._init_component()
  File "/data0/sina_cre/install/python/lib/python2.7/site-packages/pyleus/storm/component.py", line 306, in _init_component
    self._create_pidfile(setup_info['pidDir'], pid)
```

(4)code debug
303         setup_info = self._serializer.read_msg()

when 'setup_info' printed on screen, it will be integer.

**Comment by poros** [comment]
Please upgrade to Storm-0.9.2 and try again. We are not sure Pyleus is going to work with older Storm releases.

**Comment by a-whitej** [comment]
yes. It works after upgrade to Storm-0.9.2. 

Thank you.

But It is still failure when upgrade to Storm-0.9.3.
