### ISSUE TITLE
bolt died because the read_tuple() has TypeError: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by n1epan** [Yelp/pyleus#109]
I have a bolt A that continuously emits a namedtuple that contains a list that could have thousands of ids in it. The bolt B in the downstream have the error below. My guess is that the namedtuple is overflowing the sys.stdin. Is my guess correct? What I should do in this case ?

30 03/31/2015 02:56:29 PM - pyleus.storm.component - run - ERROR: Exception in bolt.run
 31 Traceback (most recent call last):                                                                                      
 32   File "/usr/lib/python2.7/site-packages/pyleus/storm/component.py", line 233, in run
 33     self.run_component()                                                                                                
 34   File "/usr/lib/python2.7/site-packages/pyleus/storm/bolt.py", line 45, in run_component
 35     tup = self.read_tuple()                                                                                             
 36   File "/usr/lib/python2.7/site-packages/pyleus/storm/component.py", line 291, in read_tuple
 37     cmd['id'], cmd['comp'], cmd['stream'], cmd['task'], cmd['tuple'])                                                   
 38 TypeError: 'int' object has no attribute '__getitem__'

**Comment by poros** [comment]
Can you try to run it locally and to debug the issue? I run a topology with some tuples in the order of the MB some time ago and it seemed to work fine (with some Storm tweaks).

**Comment by n1epan** [comment]
The issues is because the msgs are too long for msgpack to handle. After I switch to json, it worked.

**Comment by poros** [comment]
Ah, so this is actually a bug of our msgpack serializer. Good to know, thanks
