### ISSUE TITLE
bash: pyleus_venv/bin/python: No such file or directory

### ISSUE THREAD

**Issue by cyrilliang** [Yelp/pyleus#130]
When I run the example demo in local mode,it occur this exception. The trace like this:

```
    5583 [Thread-9-formatting] ERROR backtype.storm.util - Async loop died!
    java.lang.RuntimeException: Error when launching multilang subprocess
    chmod: cannot access `pyleus_venv/bin/python': No such file or directory
    bash: pyleus_venv/bin/python: No such file or directory
    at backtype.storm.utils.ShellProcess.launch(ShellProcess.java:66) ~[storm-core-0.9.3.jar:0.9.3]
    at backtype.storm.task.ShellBolt.prepare(ShellBolt.java:117) ~[storm-core-0.9.3.jar:0.9.3]
    at backtype.storm.daemon.executor$fn__3441$fn__3453.invoke(executor.clj:692) ~[storm-core-0.9.3.jar:0.9.3]
    at backtype.storm.util$async_loop$fn__464.invoke(util.clj:461) ~[storm-core-0.9.3.jar:0.9.3]
    at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
```

Caused by:

```
    java.io.IOException: Stream closed
    at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433) ~[na:1.8.0_20]
    at java.io.OutputStream.write(OutputStream.java:116) ~[na:1.8.0_20]
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_20]
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[na:1.8.0_20]
    at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[na:1.8.0_20]
    at backtype.storm.multilang.JsonSerializer.writeString(JsonSerializer.java:96) ~[storm-core-0.9.3.jar:0.9.3]
    at backtype.storm.multilang.JsonSerializer.writeMessage(JsonSerializer.java:89) ~[storm-core-0.9.3.jar:0.9.3]
    at backtype.storm.multilang.JsonSerializer.connect(JsonSerializer.java:61) ~[storm-core-0.9.3.jar:0.9.3]
    at backtype.storm.utils.ShellProcess.launch(ShellProcess.java:64) ~[storm-core-0.9.3.jar:0.9.3]
    ... 5 common frames omitted
```

What problem with it?

**Comment by fcfangcc** [comment]
i  also have this problem.then ,how to Solve this problem？

**Comment by poros** [comment]
I haven't seen this failure before, so I'd need a bit more info to be able to help.
Which operating system are you using? Which python/pyleus/storm version? Have you got virtualenv installed on your machine?

**Comment by fcfangcc** [comment]
i use centos6.6 and python2.6.6 and storm0.9.3.
 virtualenv  will install when pip install pyleus
but it is Strange.
today i build a new storm cluster ,same as (centos6.6 and python2.6.6 and storm0.9.3),then it can run!!!

**Comment by poros** [comment]
I'm sorry, I didn't understand whether pyleus is running without problems on your new cluster or not.

**Comment by cyrilliang** [comment]
It seems OK when I run the code in a fresh environment under local mode.In the old environment, it works fine under the cluster mode.

在 2015-08-25 15:46:03，"fcfangcc" notifications@github.com 写道：

i also have this problem.then ,how to Solve this problem？
