### ISSUE TITLE
OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by yatharthsharma** [Yelp/pyleus#136]
hi ,

I am new to storm. I am getting the following error:  when i run pyleus local topology_name.jar

Traceback (most recent call last):
  File "/usr/local/bin/pyleus", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/pyleus/cli/cli.py", line 54, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/pyleus/cli/commands/subcommand.py", line 105, in run_subcommand
    self.run(configs)
  File "/usr/local/lib/python2.7/dist-packages/pyleus/cli/commands/run_subcommand.py", line 42, in run
    self.run_topology(jar_path, configs)
  File "/usr/local/lib/python2.7/dist-packages/pyleus/cli/commands/local_subcommand.py", line 24, in run_topology
    run_topology_locally(jar_path, configs)
  File "/usr/local/lib/python2.7/dist-packages/pyleus/cli/topologies.py", line 27, in run_topology_locally
    configs.jvm_opts)
  File "/usr/local/lib/python2.7/dist-packages/pyleus/cli/storm_cluster.py", line 152, in run
    proc = subprocess.Popen(storm_cmd, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by BlueKarl** [comment]
same to you , wait for reply~

**Comment by poros** [comment]
Could you give a bit more details about your environment (OS, Storm version, etc)? Could it be that a log file with the same name you guys are using has already been created by another user?

**Comment by yatharthsharma** [comment]
Sorry I should have replied back after the issue was resolved. It worked after adding storm path in ~/.pyleus.conf as mentioned in the documentation.

**Comment by BlueKarl** [comment]
It's my fault! i installed Storm version 0.10.0 , when i installed storm version 0.9.2,it's ok!
