### ISSUE TITLE
kafka problems

### ISSUE THREAD

**Issue by BlueKarl** [Yelp/pyleus#156]
I write a kafka yaml : 
    name: QOStest

topology:

```
- spout:
    name: kafka-log
    type: kafka
    options:
        topic: abc
        zk_hosts: 10.10.10.10:2181
        zk_root: /pyleus-kafka-offset/QOStest
        consumer_id: pyleus-QOStest
        from_start: false
        start_offset_time: 1398971060

- bolt:
    name: re_log
    module: QOStest.re_log
    parallelism_hint: 3
    groupings:
        - global_grouping: kafka-log
```

I build it successed
when I write "pyleus local -d QOStest", It's error:
       7048 [Thread-9-kafka-log] INFO  storm.kafka.PartitionManager - Read partition information from: /pyleus-kafka-offset/QOStest/pyleus-kafka-log/partition_6  --> null
       7053 [Thread-11-re_log] INFO  backtype.storm.task.ShellBolt - Launched subprocess with pid 4031
       7054 [Thread-11-re_log] INFO  backtype.storm.daemon.executor - Prepared bolt re_log:(3)
       7154 [Thread-9-kafka-log] ERROR backtype.storm.util - Async loop died!
java.lang.RuntimeException: java.nio.channels.UnresolvedAddressException
    at storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:103) ~[QOStest.jar:na]
    at storm.kafka.ZkCoordinator.getMyManagedPartitions(ZkCoordinator.java:69) ~[QOStest.jar:na]
    at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:135) ~[QOStest.jar:na]
    at backtype.storm.daemon.executor$fn__5573$fn__5588$fn__5617.invoke(executor.clj:563) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
    at backtype.storm.util$async_loop$fn__457.invoke(util.clj:431) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
    at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]
Caused by: java.nio.channels.UnresolvedAddressException: null
    at sun.nio.ch.Net.checkAddress(Net.java:107) ~[na:1.7.0_85]
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:649) ~[na:1.7.0_85]
    at kafka.network.BlockingChannel.connect(BlockingChannel.scala:57) ~[QOStest.jar:na]
    at kafka.consumer.SimpleConsumer.connect(SimpleConsumer.scala:44) ~[QOStest.jar:na]
    at kafka.consumer.SimpleConsumer.getOrMakeConnection(SimpleConsumer.scala:142) ~[QOStest.jar:na]
    at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:69) ~[QOStest.jar:na]
    at kafka.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:124) ~[QOStest.jar:na]
    at kafka.javaapi.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:79) ~[QOStest.jar:na]
    at storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:77) ~[QOStest.jar:na]
    at storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:67) ~[QOStest.jar:na]
    at storm.kafka.PartitionManager.<init>(PartitionManager.java:83) ~[QOStest.jar:na]
    at storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:98) ~[QOStest.jar:na]
    ... 6 common frames omitted
7155 [Thread-9-kafka-log] ERROR backtype.storm.daemon.executor -
java.lang.RuntimeException: java.nio.channels.UnresolvedAddressException
    at storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:103) ~[QOStest.jar:na]
    at storm.kafka.ZkCoordinator.getMyManagedPartitions(ZkCoordinator.java:69) ~[QOStest.jar:na]
    at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:135) ~[QOStest.jar:na]
    at backtype.storm.daemon.executor$fn__5573$fn__5588$fn__5617.invoke(executor.clj:563) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
    at backtype.storm.util$async_loop$fn__457.invoke(util.clj:431) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
    at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]
Caused by: java.nio.channels.UnresolvedAddressException: null
    at sun.nio.ch.Net.checkAddress(Net.java:107) ~[na:1.7.0_85]
    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:649) ~[na:1.7.0_85]
    at kafka.network.BlockingChannel.connect(BlockingChannel.scala:57) ~[QOStest.jar:na]
    at kafka.consumer.SimpleConsumer.connect(SimpleConsumer.scala:44) ~[QOStest.jar:na]
    at kafka.consumer.SimpleConsumer.getOrMakeConnection(SimpleConsumer.scala:142) ~[QOStest.jar:na]
    at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:69) ~[QOStest.jar:na]
    at kafka.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:124) ~[QOStest.jar:na]
    at kafka.javaapi.consumer.SimpleConsumer.getOffsetsBefore(SimpleConsumer.scala:79) ~[QOStest.jar:na]
    at storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:77) ~[QOStest.jar:na]
    at storm.kafka.KafkaUtils.getOffset(KafkaUtils.java:67) ~[QOStest.jar:na]
    at storm.kafka.PartitionManager.<init>(PartitionManager.java:83) ~[QOStest.jar:na]
    at storm.kafka.ZkCoordinator.refresh(ZkCoordinator.java:98) ~[QOStest.jar:na]
    ... 6 common frames omitted
7165 [Thread-9-kafka-log] INFO  backtype.storm.util - Halting process: ("Worker died")
pyleus local: error: [StormError] Storm command failed. Run with --verbose for more info.

I wonder how to solve it? thank you .....:P

**Comment by BlueKarl** [comment]
It solved! thankyou
