### ISSUE TITLE
exclamation_topology java.lang.RuntimeException

### ISSUE THREAD

**Issue by mazhechao** [Yelp/pyleus#29]
I got a runtime exception when I submit exclamation_topology to my storm cluster both in spouts and bolts.

java.lang.RuntimeException: Error when launching multilang subprocess Traceback (most recent call last): File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main "__main__", fname,

ptyhon:2.6.6
Java:1.6
storm:0.9.2

**Comment by moandcompany** [comment]
I ran into this issue with a newly modified topology that had previously worked in local and nimbus mode.

Installing Pyleus on all of the Storm Supervisors appeared to have resolved the issue. Seems similar to my experiences with Hadoop (Streaming) where all referenced libraries need to be installed on the executing compute/worker nodes.

One of the modifications I made with this topology was a new module import in one of the bolts. It required use of the 'system_site_packages: true' option in my Pyleus configuration in order to 'build' correctly.


Here's a copy of the start of the error stack if it helps with resolving the mystery.

2015-01-28 23:36:21 b.s.t.ShellBolt [ERROR] Halting process: ShellBolt died.
java.io.EOFException: null
	at org.msgpack.io.StreamInput.readByte(StreamInput.java:60) ~[stormjar.jar:na]
	at org.msgpack.unpacker.MessagePackUnpacker.getHeadByte(MessagePackUnpacker.java:66) ~[stormjar.jar:na]
	at org.msgpack.unpacker.MessagePackUnpacker.trySkipNil(MessagePackUnpacker.java:396) ~[stormjar.jar:na]
	at org.msgpack.template.MapTemplate.read(MapTemplate.java:59) ~[stormjar.jar:na]
	at org.msgpack.template.MapTemplate.read(MapTemplate.java:27) ~[stormjar.jar:na]
	at org.msgpack.template.AbstractTemplate.read(AbstractTemplate.java:31) ~[stormjar.jar:na]
	at org.msgpack.MessagePack.read(MessagePack.java:527) ~[stormjar.jar:na]
	at org.msgpack.MessagePack.read(MessagePack.java:496) ~[stormjar.jar:na]
	at com.yelp.pyleus.serializer.MessagePackSerializer.readMessage(MessagePackSerializer.java:198) ~[stormjar.jar:na]
	at com.yelp.pyleus.serializer.MessagePackSerializer.readShellMsg(MessagePackSerializer.java:74) ~[stormjar.jar:na]
	at backtype.storm.utils.ShellProcess.readShellMsg(ShellProcess.java:99) ~[storm-core-0.9.3.2.2.0.0-2041.jar:0.9.3.2.2.0.0-2041]
	at backtype.storm.task.ShellBolt$1.run(ShellBolt.java:116) ~[storm-core-0.9.3.2.2.0.0-2041.jar:0.9.3.2.2.0.0-2041]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]

**Comment by poros** [comment]
The point is that this _should_ be actually true: you don't really need to install Pyleus on your Storm cluster to make it work. But if you are using "system_site_packages: true" and your development machine environment does not match the Storm cluster environment, well, you are going to run into issues. Having pyleus installed in your development machine and using that option _does_ actually imply that you need to have pyleus installed on your Storm cluster as well.

However, you got a point. I'll update the docs to be more explicit about that, since it easily leads to confusion.

**Comment by moandcompany** [comment]
There seem to be a few cases where trying to use 'pyleus build' with "system_site_packages: false" causes build errors, stemming from pyleus not being able to find a package to include in the new virtualenv, while the package exists in local system site packages.

Switching "system_site_packages" to 'true' allows the build to complete but resulted in Topology execution failures on a Storm cluster, unless Pyleus, itself, is also installed on the Storm custer.

**Comment by n1epan** [comment]
CentOS Linux release 7.0.1406 (Core)
apache-storm-0.9.2-incubating
virtualenv 12.0.7
I only had pyleus installed in virtual env
when I do pyleus local exclamation_topology.jar
it gave me the error:

>6105 [Thread-4] INFO  backtype.storm.daemon.worker - Worker 20c62a54-b023-465b-be8c-0e524c5e8c00 for storm exclamation_topology-1-1424195163 on 6fa94e84-b431-438a-99bf-e011e282adc7:1024 has finished loading
6124 [Thread-9-exclaim1] ERROR backtype.storm.util - Async loop died!
java.lang.RuntimeException: Error when launching multilang subprocess
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/6087e68f-0218-4ecd-b9f2-be195eacb15e/supervisor/stormdist/exclamation_topology-1-1424195163/resources/exclamation_topology/exclamation_bolt.py", line 5, in <module>
    from pyleus.storm import SimpleBolt
ImportError: No module named pyleus.storm


This error goes away when I pip install pyleus globally.

**Comment by jwestboston** [comment]
I have hit this issue on CentOS 7.  Seems that I need to install Pyleus on all of my storm supervisor nodes in order for it to operate.

**Comment by grant-traynor** [comment]
I've run into this also. It seems that if you have a pyleus.conf file, and pass in **anything at all** for
`#system_site_packages: False` then the jar creation logic does not include the pyleus package in the install. I've set it to "false" and "False" and "true" and "True" and get the same behaviour.

The only way to avoid the problem is to either (1) install pyleus on the supervisor nodes or (2) leave this line out of the config file all together.

pyleus -c pyleus.conf --verbose build pyleus_topology.yaml
pyleus -c pyleus.conf --verbose submit switchdin-primary.jar

Note: pyleus installed everywhere by pip.

**Comment by grant-traynor** [comment]
```
/src/platform/pyleusTrail# cat pyleus.conf 

[storm]
storm_cmd_path: /usr/bin/storm

# optional: use -n option of pyleus CLI instead
nimbus_host: <Nimbus Host>

# optional: use -p option of pyleus CLI instead
nimbus_port: <nimbus port>

# java options to pass to Storm CLI
#jvm_opts: -Djava.io.tmpdir=/home/myuser/tmp

[build]
# PyPI server to use during the build of your topologies
#pypi_index_url: http://pypi.ninjacorp.com/simple/

# always use system-site-packages for pyleus virtualenvs (default: false)
# Note: This settings seems to break the download of pyleus regardless of what it is set to.
# Comment raised on project git page.
#system_site_packages: False

# list of packages to always include in your topologies
#include_packages: pyleus==0.3.0
```

**Comment by jayadevanm** [comment]
I too was running into this issue. I tried leaving out the system_site_packages line and it did not help. Installed virtualenv and pyleus on all nodes and bingo, it worked.
